version: "3.7"
services:
  db:
    image: "mysql:8.0"
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: bookstore_dev
      MYSQL_USER: developer
      MYSQL_PASSWORD: cB3QM12NsD
      MYSQL_ROOT_PASSWORD: aB4S5FSM1sAdjK
    volumes:
        - ./db-bootstrap/dump.sql:/docker-entrypoint-initdb.d/dump.sql
  backend:
    build: ./backend
    restart: on-failure
    ports:
      - 8081:8081
    depends_on:
      - db
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 4200:4200